version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=emathdb
      - POSTGRES_USER=yaozhilu
      - POSTGRES_PASSWORD=dell1234
    ports:
      - "5432:5432"
  django:
    build: ./backend
    command: ["python", "./backend/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/eMath/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - .:/emath/frontend
      - /emath/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  postgres_data: