# Generated by Django 2.2.1 on 2019-06-03 19:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('isPage', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_type', models.CharField(max_length=30)),
                ('html_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.IntegerField()),
                ('para_type', models.CharField(max_length=15)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('para_upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_next', to='database.Level')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='MathDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('content', models.TextField()),
                ('math_display_upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_display_next', to='database.Level')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='level',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='database.Person'),
        ),
        migrations.AddField(
            model_name='level',
            name='contributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='database.Person'),
        ),
        migrations.AddField(
            model_name='level',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.Level'),
        ),
    ]
