# Generated by Django 2.2.1 on 2019-05-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('isPage', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100, null=True)),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Level')),
            ],
        ),
        migrations.CreateModel(
            name='MathDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='MiniCompositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.IntegerField()),
                ('para_type', models.CharField(max_length=15)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('upper_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Level')),
                ('upper_mini_compositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.MiniCompositor')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('external_link', models.ManyToManyField(to='database.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.Level')),
                ('html_title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.ManyToManyField(related_name='author', to='database.Person')),
                ('contributor', models.ManyToManyField(related_name='contributors', to='database.Person')),
            ],
            bases=('database.level',),
        ),
    ]
