# Generated by Django 2.2.1 on 2019-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(default='Book', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='contributor',
            field=models.ManyToManyField(null=True, related_name='contributors', to='database.Person'),
        ),
    ]
