# Generated by Django 2.2.1 on 2019-07-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='database.Person'),
        ),
        migrations.AlterField(
            model_name='level',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='database.Person'),
        ),
        migrations.RemoveField(
            model_name='para',
            name='para_upper',
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('parent_i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_parent_id', to='database.Para')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to', to='database.Level')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('target', models.BooleanField()),
                ('parent_e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_parent_id', to='database.Para')),
            ],
        ),
        migrations.AddField(
            model_name='para',
            name='para_upper',
            field=models.ManyToManyField(related_name='para_next', through='database.InternalLink', to='database.Level'),
        ),
    ]
