# Generated by Django 2.2.1 on 2019-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_level_pagenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='pageNum',
            field=models.IntegerField(blank=True),
        ),
    ]
