# Generated by Django 2.2.1 on 2019-05-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190529_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='upper_mini_compositor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.MiniCompositor'),
        ),
    ]
