# Generated by Django 2.2.1 on 2019-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190715_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='pageNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
