# Generated by Django 2.2.1 on 2019-05-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190529_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para',
            name='upper_mini_compositor',
        ),
        migrations.DeleteModel(
            name='MiniCompositor',
        ),
    ]
