# Generated by Django 2.2.1 on 2019-05-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190530_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='unit_type',
        ),
    ]
