# Generated by Django 2.2.1 on 2019-08-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190718_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathdisplay',
            name='math_display_upper',
        ),
        migrations.DeleteModel(
            name='InternalLink',
        ),
        migrations.DeleteModel(
            name='MathDisplay',
        ),
    ]
