# Generated by Django 2.2.1 on 2019-05-31 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190531_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='contributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='database.Person'),
        ),
        migrations.AlterField(
            model_name='level',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='para',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
