# Generated by Django 2.2.1 on 2019-08-23 20:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190823_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='para',
            name='content1',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='para',
            name='content',
            field=models.TextField(),
        ),
    ]
