# Generated by Django 2.2.1 on 2019-08-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190823_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para',
            name='content1',
        ),
    ]
