# Generated by Django 2.2.1 on 2019-08-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190823_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para',
            name='para_type',
        ),
    ]
