# Generated by Django 2.2.1 on 2019-09-03 17:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_para_para_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'list': '', 'table': '', 'text': ''}),
        ),
    ]
