# Generated by Django 2.2.1 on 2019-09-16 17:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import presentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=presentation.models.default_para_dict),
        ),
    ]
