# Generated by Django 2.2.1 on 2019-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20190916_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to='presentation.Person'),
        ),
        migrations.AlterField(
            model_name='level',
            name='contributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='presentation.Person'),
        ),
    ]
