# Generated by Django 2.2.1 on 2019-10-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_auto_20191016_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
