# Generated by Django 2.2.1 on 2019-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_auto_20191022_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='unit_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
