# Generated by Django 2.2.1 on 2019-11-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_auto_20191031_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='author',
        ),
        migrations.RemoveField(
            model_name='level',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='level',
            name='date',
        ),
        migrations.RemoveField(
            model_name='level',
            name='html_title',
        ),
    ]
