# Generated by Django 2.2.1 on 2019-12-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0010_auto_20191107_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para',
            name='caption',
        ),
        migrations.AlterField(
            model_name='level',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.RootLevel'),
        ),
    ]
