# Generated by Django 2.2.1 on 2020-01-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0012_auto_20200106_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.RootLevel'),
        ),
    ]
