# Generated by Django 2.2.1 on 2020-03-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0017_auto_20200213_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootlevel',
            old_name='glossary',
            new_name='index_item',
        ),
        migrations.AlterField(
            model_name='level',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.RootLevel'),
        ),
    ]
