# Generated by Django 2.2.1 on 2020-05-18 17:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0019_auto_20200311_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootlevel',
            name='tex_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'basicCommand': ['\\Defn{ConceptToBeDefined}', '\\AnglBr{arg1}', '\\SqBr{arg1}', '\\DSqBr{arg1}', '\\dsqrl', '\\dsqrr', '\\dsbo', '\\dsbc', '\\prdct', '\\Prdct{factor1}{factor2}', '\\PPrdct{factor1}{factor2}{factor3}', '\\PPPPrdct{factor1}{factor2}{factor3}{factor4}{factor5}', '\\FamPrdct{IndexSet}{Objects}', '\\PrjctnOnto{factor}', '\\PrjctnOntoOf{factor}{element}', '\\PrjctnOntoOfCoord{factor}{TupleInBrackets}', '\\Set{ListOfElements}', '\\SetSlct{Elements}{Property}', '\\union', '\\dunion', '\\Union{Set1}{Set2}', '\\FamUnion{IndexSet}{Sets}', '\\intrsctn', '\\dintrsctn', '\\SetIntrsctn{Set1}{Set2}', '\\FamIntrsctn{IndexSet}{Sets}', '\\SetDffrnc{Set1}{Set2}', '\\SetPrdct{Set1}{Set2}', '\\SetCoPrdct{Set1}{Set2}', '\\PwrSt{SetToBePowered}', '\\coprdct', '\\CoPrdct{Object1}{Object2}', '\\FamCoPrdct{IndexSet}{Objects}', '\\ExpExchng{Functor}', '\\Card{Set}', '\\Img{Morphism}', '\\ImgFnctr', '\\IdMap', '\\IdMapOn{Object}', '\\OneMap', '\\OneMapOn{Object}', '\\Inclsn', '\\InclsnOf{Object}', '\\evltn', '\\Evltn{At}', '\\Dgnl', '\\DgnlOn{Object}', '\\NNr', '\\ZNr', '\\QNr', '\\RNr', '\\CNr', '\\CNrSpc{ComplexDimension}', '\\OctNrSpc{QuaternionDimension}', '\\QuatNrSpc{QuaternionDimension}', '\\QNrSpc{RationalDimension}', '\\RNrSpc{RealDimension}', '\\ImPrt{ComplexNumber}', '\\RePrt{ComplexNumber}', '\\CCnjgt{ComplexNumber}', '\\CAbs{ComplexNumber}', '\\CCIntrvl{LeftLimit}{RightLimit}', '\\COIntrvl{LeftLimit}{RightLimit}', '\\OCIntrvl{LeftLimit}{RightLimit}', '\\OOIntrvl{LeftLimit}{RightLimit}', '\\Norm{Vector}', '\\Abs{Number}', '\\Sign{Number}', '\\Min{Set}', '\\Max{Set}', '\\ZMod{p}', '\\FFld{FieldOrder}', '\\ZLocal{PrimeNumber}', '\\ZLocalSet{SetOfPrimes}', '\\ZInfty{PrimeNumber}', '\\PAdicZ{CompletedAt}', '\\ProFCmpltnZ', '\\PAdicQ{PrimeNumber}', '\\ProFCmpltnQ\\Poly{Ring}{Variables}', '\\PolyDeg{Polynomial}', '\\ZPoly{Variable}', '\\QPoly{Variable}', '\\RPoly{Variable}', '\\CPoly{Variable}', '\\CyclcGrp{Order}', '\\AltGrp{NumberElements}', '\\SymGrp{NumberElements}', '\\CUGrp{ComplexUnitaryGrpDimension}', '\\SCUGrp{SpecialComplexUnitaryGrpDimension}', '\\RUGrp{RealUnitaryGrpDimension}', '\\SRUGrp{SpecialRealUnitaryGrpDimension}', '\\SpinGrp{Dimension}', '\\GLGrp{Size}{Ring}', '\\PGLGrp{Size}{Ring}', '\\SLGrp{Size}{Ring}', '\\PSLGrp{Size}{Ring}', '\\GLMGrp{Type}', '\\CGLGrp{Size}', '\\PCGLGrp{Size}', '\\RGLGrp{Size}', '\\SRGLGrp{Size}', '\\SCGLGrp{Size}', '\\TrsGrp{Size}', '\\Hom', '\\Ker{OfMorphism}', '\\KerFunc', '\\CoKer{OfMorphism}', '\\CoKerFunc', '\\normal', '\\rnormal', '\\AutGrp{OfObject}', '\\InnGrp{OfGroup}', '\\OutGrp{OfGroup}', '\\IsoGrp{OfObject}', '\\PermGrp{OfSet}', '\\EndRng{OfObject}', '\\RSpan{OfSet}', '\\CSpan{OfSet}', '\\Span', '\\SpanOfT{Tuple}', '\\SpanOfSet{Set}', '\\Dim', '\\DimOf{Space}', '\\RDim', '\\RDimOf{Space}', '\\CDim', '\\CDimOf{Space}', '\\DtrmnntOf{Matrix}', '\\DtrmnntOfMtrx{M}', '\\Dtrmnnt', '\\Trc', '\\TrcOf{Matrix}', '\\Vol{Solid}', '\\uInt', '\\uCube{CubeDim}', '\\uBll{BallDim}', '\\uDsk', '\\uSphr{SphereDim}', '\\uCrcl', '\\Trs{TorusDim}', '\\CnvxHull{Set}', '\\TopIntr}{In}{OfSubSpace}', '\\TopClsr{In}{OfSubSpace}', '\\TopBndy{OfSubspace}', '\\LimPnts{OfSet}', '\\Dstnc{Point1}{Point2}', '\\HomeoGrp{Of}']}),
        ),
        migrations.AlterField(
            model_name='level',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.RootLevel'),
        ),
    ]
