# Generated by Django 2.2.1 on 2020-05-18 17:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import presentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0020_auto_20200518_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='root',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.RootLevel'),
        ),
        migrations.AlterField(
            model_name='rootlevel',
            name='tex_command',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=presentation.models.basic_command),
        ),
    ]
