# Generated by Django 2.2.1 on 2019-09-16 17:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('pageNum', models.IntegerField(blank=True, null=True)),
                ('isPage', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('tocTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_type', models.CharField(max_length=30)),
                ('html_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default={'list': '', 'table': '', 'text': ''})),
                ('position', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('para_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Level')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='level',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='presentation.Person'),
        ),
        migrations.AddField(
            model_name='level',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='presentation.Person'),
        ),
        migrations.AddField(
            model_name='level',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='presentation.Level'),
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('target', models.BooleanField()),
                ('parent_e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_parent_id', to='presentation.Para')),
            ],
        ),
    ]
